ValueSet: VS_GeneralLabTests
Id: VS-GeneralLabTests
Title: "一般健康檢查及體格檢查實驗室項目值集"
Description: "包含一般健康檢查及體格檢查之實驗室檢驗項目，對應至 LOINC 代碼。"
* ^experimental = false

// 1. 血液學 (Hematology)
* LNC#718-7 "Hemoglobin [Mass/volume] in Blood"
* LNC#4544-3 "Hematocrit [Volume Fraction] of Blood"
* LNC#789-8 "Erythrocytes [#/volume] in Blood"
* LNC#6690-2 "Leukocytes [#/volume] in Blood"
* LNC#777-3 "Platelets [#/volume] in Blood"
* LNC#787-2 "MCV [Entitic volume] by Automated count"
* LNC#785-6 "MCH [Entitic mass] by Automated count"
* LNC#786-4 "MCHC [Mass/volume] by Automated count"
* LNC#788-0 "Erythrocyte distribution width [Ratio] by Automated count"
* LNC#762-1 "Neutrophils/100 leukocytes in Blood by Automated count"
* LNC#770-8 "Lymphocytes/100 leukocytes in Blood by Automated count"
* LNC#850-0 "Monocytes/100 leukocytes in Blood by Automated count"
* LNC#711-2 "Eosinophils/100 leukocytes in Blood by Automated count"
* LNC#704-7 "Basophils/100 leukocytes in Blood by Automated count"
* LNC#751-4 "Neutrophils [#/volume] in Blood by Automated count"
* LNC#709-6 "Lymphocytes [#/volume] in Blood by Automated count"

// 2. 生化、腎功能與心血管風險 (Chemistry/Renal/Cardiovascular)
* LNC#1558-6 "Fasting Glucose [Mass/volume] in Serum or Plasma"
* LNC#2339-0 "Glucose [Mass/volume] in Blood"
* LNC#4548-4 "Hemoglobin A1c/Hemoglobin.total in Blood"
* LNC#15067-2 "Insulin [Units/volume] in Serum or Plasma"
* LNC#95574-0 "HOMA-IR panel"
* LNC#2160-0 "Creatinine [Mass/volume] in Serum or Plasma"
* LNC#3094-0 "Urea nitrogen [Mass/volume] in Serum or Plasma"
* LNC#33914-3 "Glomerular filtration rate/1.73 sq M.predicted by MDRD equation"
* LNC#88293-6 "Glomerular filtration rate/1.73 sq M.predicted by Creatinine-based formula (CKD-EPI 2021)"
* LNC#33863-2 "Cystatin C [Mass/volume] in Serum, Plasma or Blood"
* LNC#3084-1 "Uric acid [Mass/volume] in Serum or Plasma"
* LNC#17861-6 "Calcium [Mass/volume] in Serum or Plasma"
* LNC#2777-1 "Phosphate [Mass/volume] in Serum or Plasma"
* LNC#30522-7 "C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method"
* LNC#2428-1 "Homocysteine [Moles/volume] in Serum or Plasma"

// 3. 肝膽、胰臟與心肌功能 (Liver/Pancreas/Cardiac)
* LNC#1920-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#1742-6 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#6768-6 "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#2324-2 "Gamma glutamyltransferase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#1975-2 "Bilirubin.total [Mass/volume] in Serum or Plasma"
* LNC#1968-7 "Bilirubin.direct [Mass/volume] in Serum or Plasma"
* LNC#1751-7 "Albumin [Mass/volume] in Serum or Plasma"
* LNC#2885-2 "Protein [Mass/volume] in Serum or Plasma"
* LNC#1759-0 "Globulin [Mass/volume] in Serum or Plasma"
* LNC#1754-1 "Albumin/Globulin [Mass Ratio] in Serum or Plasma"
* LNC#2532-0 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#1798-8 "Amylase [Enzymatic activity/volume] in Serum or Plasma"
* LNC#3040-3 "Lipase [Enzymatic activity/volume] in Serum or Plasma"

// 4. 脂質分析 (Lipids)
* LNC#2093-3 "Cholesterol [Mass/volume] in Serum or Plasma"
* LNC#2571-8 "Triglyceride [Mass/volume] in Serum or Plasma"
* LNC#2085-9 "Cholesterol in HDL [Mass/volume] in Serum or Plasma"
* LNC#13457-7 "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation"
* LNC#18262-6 "Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay"
* LNC#46986-6 "Cholesterol in VLDL [Mass/volume] in Serum or Plasma by calculation"
* LNC#9830-1 "Cholesterol/Cholesterol in HDL [Mass Ratio] in Serum or Plasma"

// 5. 甲狀腺與營養指標 (Thyroid/Nutrition)
* LNC#11580-8 "Thyrotropin [Units/volume] in Serum or Plasma"
* LNC#3026-9 "Thyroxine (T4) free [Mass/volume] in Serum or Plasma"
* LNC#3016-0 "Triiodothyronine (T3) free [Mass/volume] in Serum or Plasma"
* LNC#8272-9 "Thyroxine (T4) total [Mass/volume] in Serum or Plasma"
* LNC#1647-8 "Triiodothyronine (T3) total [Mass/volume] in Serum or Plasma"
* LNC#8099-4 "Thyroid peroxidase Ab [Units/volume] in Serum or Plasma"
* LNC#62292-8 "25-hydroxyvitamin D3 [Mass/volume] in Serum or Plasma"
* LNC#2132-9 "Cobalamin (Vitamin B12) [Mass/volume] in Serum or Plasma"
* LNC#2284-0 "Folate [Mass/volume] in Serum or Plasma"

// 6. 癌症篩檢與 PHI (Cancer Markers/PHI)
* LNC#19177-3 "Alpha-1-fetoprotein [Mass/volume] in Serum or Plasma"
* LNC#19170-8 "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma"
* LNC#2857-1 "Prostate specific Ag [Mass/volume] in Serum or Plasma"
* LNC#10886-0 "Prostate specific Ag.free [Mass/volume] in Serum or Plasma"
* LNC#57762-7 "proPSA.inactive [Mass/volume] in Serum or Plasma"
* LNC#77621-1 "Prostate Health Index"
* LNC#83076-7 "Cancer Ag 125 [Units/volume] in Serum or Plasma"
* LNC#83084-1 "Cancer Ag 19-9 [Units/volume] in Serum or Plasma"
* LNC#83081-7 "Cancer Ag 15-3 [Units/volume] in Serum or Plasma"
* LNC#19198-9 "Squamous cell carcinoma Ag [Mass/volume] in Serum or Plasma"
* LNC#50756-6 "Epstein Barr virus VCA IgA Ab [Presence] in Serum"

// 7. 傳染病、HPV與胃部篩檢 (Infections/HPV/Stomach)
* LNC#51853-0 "Hepatitis B virus surface Ag [Presence] in Serum"
* LNC#22322-2 "Hepatitis B virus surface Ab [Units/volume] in Serum"
* LNC#13955-0 "Hepatitis C virus Ab [Presence] in Serum or Plasma"
* LNC#20507-0 "Reagin Ab [Presence] in Serum by RPR"
* LNC#51651-8 "Treponema pallidum Ab [Presence] in Serum"
* LNC#56888-1 "HIV 1 and 2 Ag and Ab panel [Presence] in Serum or Plasma"
* LNC#13944-4 "Helicobacter pylori IgG Ab [Presence] in Serum"
* LNC#15497-1 "Helicobacter pylori Ag [Presence] in Stool"
* LNC#29771-3 "Hemoglobin.occult [Mass/volume] in Stool by Immunochemical method"
* LNC#49892-3 "Human papilloma virus 16 and 18 and high risk DNA [Presence] in Cervix by Probe"

// 8. 尿液常規 (Urinalysis)
* LNC#5790-1 "pH of Urine by Test strip"
* LNC#5804-0 "Protein [Presence] in Urine by Test strip"
* LNC#5792-7 "Glucose [Presence] in Urine by Test strip"
* LNC#5794-3 "Hemoglobin [Presence] in Urine by Test strip"
* LNC#5797-6 "Ketones [Presence] in Urine by Test strip"
* LNC#5799-2 "Nitrite [Presence] in Urine by Test strip"
* LNC#5770-3 "Bilirubin [Presence] in Urine by Test strip"
* LNC#5802-4 "Urobilinogen [Presence] in Urine by Test strip"
* LNC#29400-9 "Specific gravity of Urine"
* LNC#5798-4 "Leukocyte esterase [Presence] in Urine by Test strip"
* LNC#5821-6 "Erythrocytes [#/area] in Urine sediment by Light microscopy"
* LNC#5822-4 "Leukocytes [#/area] in Urine sediment by Light microscopy"
* LNC#5777-8 "Epithelial cells [#/area] in Urine sediment by Light microscopy"
* LNC#5786-9 "Casts [#/area] in Urine sediment by Light microscopy"
* LNC#25145-4 "Bacteria [Presence] in Urine sediment by Light microscopy"

// 9. 進階心血管、自體免疫與其它 (Advanced Cardiac/Autoimmune/Others)
* LNC#10835-7 "Lipoprotein A [Mass/volume] in Serum or Plasma"
* LNC#1855-0 "Apolipoprotein A-I [Mass/volume] in Serum or Plasma"
* LNC#1871-7 "Apolipoprotein B [Mass/volume] in Serum or Plasma"
* LNC#33762-6 "Natriuretic peptide.proB-type N-terminal [Mass/volume] in Serum or Plasma"
* LNC#11561-8 "Antinuclear Ab [Presence] in Serum by Immunofluorescence"
* LNC#11572-5 "Rheumatoid factor [Units/volume] in Serum or Plasma"
* LNC#1988-5 "C reactive protein [Mass/volume] in Serum or Plasma"
* LNC#13705-9 "Albumin/Creatinine [Mass Ratio] in Urine"
* LNC#14957-5 "Microalbumin [Mass/volume] in Urine"
* LNC#2161-8 "Creatinine [Mass/volume] in Urine"
* LNC#30325-5 "Hemoglobin H/Hemoglobin.total in Blood"
* LNC#34237-8 "CYFRA 21-1 [Mass/volume] in Serum or Plasma"
