Instance: Appendix10-to-HazardType
InstanceOf: ConceptMap
Usage: #definition
* url = "https://twcore.mohw.gov.tw/ig/twha/ConceptMap/Appendix10-to-HazardType"
* name = "Appendix10ToHazardType"
* title = "附表十 35 項法定作業 對 12 危害家族 對照"
* description = "將 CS-Appendix10Operation（附表十 35 項具名作業）對映至 CS-HazardType（12 危害家族）。每一具名作業（source）相對於其對應之危害家族（target）在語意上較窄，故 equivalence = narrower（家族涵蓋範圍較廣）。供接收端由法定作業編號歸併至危害家族，回應審查意見之逐號可追溯性需求。"
* status = #active
* experimental = false
* sourceCanonical = "https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-Appendix10-Operation"
* targetCanonical = "https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-HazardType"
* group[0].source = "https://twcore.mohw.gov.tw/ig/twha/CodeSystem/CS-Appendix10Operation"
* group[0].target = "https://twcore.mohw.gov.tw/ig/twha/CodeSystem/CS-HazardType"
* group[0].element[0].code = #app-01
* group[0].element[0].display = "高溫作業"
* group[0].element[0].target[0].code = #high-temp
* group[0].element[0].target[0].equivalence = #narrower
* group[0].element[0].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[1].code = #app-02
* group[0].element[1].display = "噪音作業"
* group[0].element[1].target[0].code = #noise
* group[0].element[1].target[0].equivalence = #narrower
* group[0].element[1].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[2].code = #app-03
* group[0].element[2].display = "游離輻射作業"
* group[0].element[2].target[0].code = #radiation
* group[0].element[2].target[0].equivalence = #narrower
* group[0].element[2].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[3].code = #app-04
* group[0].element[3].display = "異常氣壓作業"
* group[0].element[3].target[0].code = #abnormal-pressure
* group[0].element[3].target[0].equivalence = #narrower
* group[0].element[3].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[4].code = #app-05
* group[0].element[4].display = "鉛作業"
* group[0].element[4].target[0].code = #lead
* group[0].element[4].target[0].equivalence = #narrower
* group[0].element[4].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[5].code = #app-06
* group[0].element[5].display = "四烷基鉛作業"
* group[0].element[5].target[0].code = #tetraalkyl-lead
* group[0].element[5].target[0].equivalence = #narrower
* group[0].element[5].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[6].code = #app-07
* group[0].element[6].display = "1,1,2,2-四氯乙烷作業"
* group[0].element[6].target[0].code = #organic-solvent
* group[0].element[6].target[0].equivalence = #narrower
* group[0].element[6].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[7].code = #app-08
* group[0].element[7].display = "四氯化碳作業"
* group[0].element[7].target[0].code = #organic-solvent
* group[0].element[7].target[0].equivalence = #narrower
* group[0].element[7].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[8].code = #app-09
* group[0].element[8].display = "二硫化碳作業"
* group[0].element[8].target[0].code = #organic-solvent
* group[0].element[8].target[0].equivalence = #narrower
* group[0].element[8].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[9].code = #app-10
* group[0].element[9].display = "三氯乙烯作業"
* group[0].element[9].target[0].code = #organic-solvent
* group[0].element[9].target[0].equivalence = #narrower
* group[0].element[9].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[10].code = #app-11
* group[0].element[10].display = "二甲基甲醯胺作業"
* group[0].element[10].target[0].code = #organic-solvent
* group[0].element[10].target[0].equivalence = #narrower
* group[0].element[10].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[11].code = #app-12
* group[0].element[11].display = "正己烷作業"
* group[0].element[11].target[0].code = #organic-solvent
* group[0].element[11].target[0].equivalence = #narrower
* group[0].element[11].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[12].code = #app-13
* group[0].element[12].display = "聯苯胺及其鹽類作業"
* group[0].element[12].target[0].code = #specific-chemical
* group[0].element[12].target[0].equivalence = #narrower
* group[0].element[12].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[13].code = #app-14
* group[0].element[13].display = "鈹及其化合物作業"
* group[0].element[13].target[0].code = #specific-chemical
* group[0].element[13].target[0].equivalence = #narrower
* group[0].element[13].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[14].code = #app-15
* group[0].element[14].display = "氯乙烯作業"
* group[0].element[14].target[0].code = #specific-chemical
* group[0].element[14].target[0].equivalence = #narrower
* group[0].element[14].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[15].code = #app-16
* group[0].element[15].display = "苯作業"
* group[0].element[15].target[0].code = #specific-chemical
* group[0].element[15].target[0].equivalence = #narrower
* group[0].element[15].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[16].code = #app-17
* group[0].element[16].display = "2,4-二異氰酸甲苯作業"
* group[0].element[16].target[0].code = #specific-chemical
* group[0].element[16].target[0].equivalence = #narrower
* group[0].element[16].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[17].code = #app-18
* group[0].element[17].display = "石綿作業"
* group[0].element[17].target[0].code = #specific-chemical
* group[0].element[17].target[0].equivalence = #narrower
* group[0].element[17].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[18].code = #app-19
* group[0].element[18].display = "砷及其化合物作業"
* group[0].element[18].target[0].code = #specific-chemical
* group[0].element[18].target[0].equivalence = #narrower
* group[0].element[18].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[19].code = #app-20
* group[0].element[19].display = "錳及其化合物作業"
* group[0].element[19].target[0].code = #specific-chemical
* group[0].element[19].target[0].equivalence = #narrower
* group[0].element[19].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[20].code = #app-21
* group[0].element[20].display = "黃磷作業"
* group[0].element[20].target[0].code = #yellow-phosphorus
* group[0].element[20].target[0].equivalence = #narrower
* group[0].element[20].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[21].code = #app-22
* group[0].element[21].display = "聯吡啶或巴拉刈作業"
* group[0].element[21].target[0].code = #paraquat
* group[0].element[21].target[0].equivalence = #narrower
* group[0].element[21].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[22].code = #app-23
* group[0].element[22].display = "粉塵作業"
* group[0].element[22].target[0].code = #dust
* group[0].element[22].target[0].equivalence = #narrower
* group[0].element[22].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[23].code = #app-24
* group[0].element[23].display = "鉻酸及其鹽類作業"
* group[0].element[23].target[0].code = #specific-chemical
* group[0].element[23].target[0].equivalence = #narrower
* group[0].element[23].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[24].code = #app-25
* group[0].element[24].display = "鎘及其化合物作業"
* group[0].element[24].target[0].code = #specific-chemical
* group[0].element[24].target[0].equivalence = #narrower
* group[0].element[24].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[25].code = #app-26
* group[0].element[25].display = "鎳及其化合物作業"
* group[0].element[25].target[0].code = #specific-chemical
* group[0].element[25].target[0].equivalence = #narrower
* group[0].element[25].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[26].code = #app-27
* group[0].element[26].display = "乙基汞化合物作業"
* group[0].element[26].target[0].code = #specific-chemical
* group[0].element[26].target[0].equivalence = #narrower
* group[0].element[26].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[27].code = #app-28
* group[0].element[27].display = "溴丙烷作業"
* group[0].element[27].target[0].code = #specific-chemical
* group[0].element[27].target[0].equivalence = #narrower
* group[0].element[27].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[28].code = #app-29
* group[0].element[28].display = "1,3-丁二烯作業"
* group[0].element[28].target[0].code = #specific-chemical
* group[0].element[28].target[0].equivalence = #narrower
* group[0].element[28].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[29].code = #app-30
* group[0].element[29].display = "甲醛作業"
* group[0].element[29].target[0].code = #specific-chemical
* group[0].element[29].target[0].equivalence = #narrower
* group[0].element[29].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[30].code = #app-31
* group[0].element[30].display = "銦及其化合物作業"
* group[0].element[30].target[0].code = #specific-chemical
* group[0].element[30].target[0].equivalence = #narrower
* group[0].element[30].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[31].code = #app-32
* group[0].element[31].display = "汞及其無機化合物作業"
* group[0].element[31].target[0].code = #specific-chemical
* group[0].element[31].target[0].equivalence = #narrower
* group[0].element[31].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[32].code = #app-33
* group[0].element[32].display = "苯乙烯作業"
* group[0].element[32].target[0].code = #organic-solvent
* group[0].element[32].target[0].equivalence = #narrower
* group[0].element[32].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[33].code = #app-34
* group[0].element[33].display = "甲苯作業"
* group[0].element[33].target[0].code = #organic-solvent
* group[0].element[33].target[0].equivalence = #narrower
* group[0].element[33].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
* group[0].element[34].code = #app-35
* group[0].element[34].display = "二甲苯作業"
* group[0].element[34].target[0].code = #organic-solvent
* group[0].element[34].target[0].equivalence = #narrower
* group[0].element[34].target[0].comment = "具名作業為該危害家族之特定成員，家族涵蓋範圍較廣（narrower：source 較 target 窄）。"
